name: Insta Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Write Google credentials
        shell: bash
        run: |
          echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Inspect credentials.json (debug)
        run: |
          wc -c credentials.json
          python - <<'PY'
import sys, json
b=open("credentials.json","rb").read()
print("first byte:", b[:1])
print("keys:", sorted(json.loads(b.decode("utf-8")).keys()))
PY

      - name: Assert hardened loader present
        run: |
          if grep -n "from_json_keyfile_name" check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
          sed -n '1,40p' check_instagram_links.py

      - name: Run script
        run: python -u check_instagram_links.py
