name: Insta Checker

on:
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Write Google credentials
        shell: bash
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Inspect credentials.json (debug)
        run: >
          python -c "import json, pathlib;
          b=pathlib.Path('credentials.json').read_bytes();
          print('first byte:', b[:1]);
          print('keys:', sorted(json.loads(b.decode('utf-8')).keys()))"

      - name: Assert hardened loader present
        shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi

      - name: Run script
        run: python -u check_instagram_links.py
