name: Instagram DMCA Link Checker

on:
  schedule:
    - cron: "0 2 * * *"  # every day at 2 AM UTC
  workflow_dispatch:      # allows manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright Browsers
        run: |
          pip install playwright
          playwright install chromium

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Write Google credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Run script
        run: python check_instagram_links.py
