name: Instagram DMCA Link Checker

on:
  workflow_dispatch: {}           # allows manual runs
  schedule:
    - cron: "0 2 * * *"           # daily at 02:00 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browser
        run: |
          python -m playwright install chromium

      - name: Write Google credentials
        run: echo "$GOOGLE_CREDS_JSON" > credentials.json
        env:
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}

      - name: Run script
        run: python check_instagram_links.py
