name: Instagram DMCA Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Playwright browsers for the Python package (chromium + deps)
      - name: Install Playwright browsers (python)
        run: |
          python -m playwright install --with-deps chromium

      # Write service account JSON from secret into credentials.json
      - name: Write Google credentials
        shell: bash
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          if [ -z "${GOOGLE_CREDENTIALS}" ]; then
            echo "ERROR: GOOGLE_CREDENTIALS secret is empty"; exit 1
          fi
          # Avoid trailing newline issues; write bytes exactly
          printf "%s" "${GOOGLE_CREDENTIALS}" > credentials.json

      # Small sanity check that the JSON is present and valid
      - name: Inspect credentials.json (debug)
        shell: bash
        run: |
          wc -c credentials.json
          python - <<'PY'
            import json, pathlib
            b = pathlib.Path("credentials.json").read_bytes()
            print("first byte:", b[:1])
            print("keys:", sorted(json.loads(b.decode("utf-8")).keys()))
PY

      # Ensure we are NOT using the deprecated keyfile loader in the script
      - name: Assert hardened loader present
        shell: bash
        run: |
          if grep -n "from_json_keyfile_name" check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
          sed -n '1,40p' check_instagram_links.py

      # Run unbuffered so logs stream live in Actions
      - name: Run script (live logs)
        run: python -u check_instagram_links.py
