# .github/workflows/insta_checker.yml
name: Insta Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'   # 10 PM EST (02:00 UTC)

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Write Google credentials
        shell: bash
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          printf '%s' "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      - name: Inspect credentials.json (debug)
        run: |
          wc -c credentials.json
          python - <<'PY'
import json, pathlib
b = pathlib.Path("credentials.json").read_bytes()
print("first byte:", b[:1])
print("keys:", sorted(json.loads(b.decode("utf-8")).keys()))
PY

      - name: Assert hardened loader present
        shell: bash
        run: |
          if grep -n "from_json_keyfile_name" check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
          sed -n '1,40p' check_instagram_links.py

      - name: Count current URLs in Logs!F
        id: count
        run: |
          TOTAL=$(python - <<'PY'
import json, gspread
from oauth2client.service_account import ServiceAccountCredentials
scope = ["https://spreadsheets.google.com/feeds","https://www.googleapis.com/auth/drive"]
with open("credentials.json","r",encoding="utf-8") as f:
    d = json.load(f)
gc = gspread.authorize(ServiceAccountCredentials.from_json_keyfile_dict(d, scope))
ws = gc.open_by_key("1fFTIEDy-86lDaCgll1GkTq376hvrTd-DXulioXrDAgw").worksheet("Logs")
col = ws.col_values(6)  # Column F
print(sum(1 for v in col[1:] if (v or "").strip()))
PY
          )
          echo "total=${TOTAL}" | tee -a "$GITHUB_OUTPUT"

      - name: Run script
        run: python -u check_instagram_links.py
