name: Insta Checker

on:
  schedule:
    - cron: "0 3 * * *"   # ~10PM ET
  workflow_dispatch:
    inputs:
      total_shards:
        description: "Total shards for manual run (e.g. 8)"
        required: false
        default: "8"
      skip_recent_days:
        description: "Skip rows whose 'Last checked' is within N days (0=off)"
        required: false
        default: "0"

jobs:
  nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        shard: [0,1,2,3,4,5,6,7]
    env:
      SHARD_INDEX: ${{ matrix.shard }}
      TOTAL_SHARDS: 8
      SKIP_RECENT_DAYS: 0
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade "playwright>=1.47.1"
          playwright install --with-deps chromium

      - name: Write Google credentials
        shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            printf '%s' "${RAW_JSON:-}" > credentials.json
          fi
          test -s credentials.json

      - name: Refuse deprecated keyfile loader
        shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi

      - name: Run checker (nightly shards)
        env:
          SHARD_INDEX: ${{ env.SHARD_INDEX }}
          TOTAL_SHARDS: ${{ env.TOTAL_SHARDS }}
          SKIP_RECENT_DAYS: ${{ env.SKIP_RECENT_DAYS }}
        run: python -u check_instagram_links.py

  prepare-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
      total:  ${{ steps.gen.outputs.total }}
      skip:   ${{ steps.gen.outputs.skip }}
    steps:
      - id: gen
        shell: bash
        run: |
          set -euo pipefail
          TOTAL="${{ github.event.inputs.total_shards || '1' }}"
          SKIP="${{ github.event.inputs.skip_recent_days || '0' }}"
          if ! [[ "$TOTAL" =~ ^[0-9]+$ && "$TOTAL" -ge 1 ]]; then TOTAL=1; fi
          seq 0 $((TOTAL-1)) | paste -sd, - | awk -v t="$TOTAL" -v s="$SKIP" '{print "matrix={\"shard\":[" $0 "]}\ntotal=" t "\nskip=" s}' >> "$GITHUB_OUTPUT"

  manual:
    if: github.event_name == 'workflow_dispatch'
    needs: prepare-manual
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-manual.outputs.matrix) }}
    env:
      SHARD_INDEX: ${{ matrix.shard }}
      TOTAL_SHARDS: ${{ needs.prepare-manual.outputs.total }}
      SKIP_RECENT_DAYS: ${{ needs.prepare-manual.outputs.skip }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade "playwright>=1.47.1"
          playwright install --with-deps chromium

      - name: Write Google credentials
        shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            printf '%s' "${RAW_JSON:-}" > credentials.json
          fi
          test -s credentials.json

      - name: Refuse deprecated keyfile loader
        shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi

      - name: Run checker (manual shards)
        env:
          SHARD_INDEX: ${{ env.SHARD_INDEX }}
          TOTAL_SHARDS: ${{ env.TOTAL_SHARDS }}
          SKIP_RECENT_DAYS: ${{ env.SKIP_RECENT_DAYS }}
        run: python -u check_instagram_links.py
