name: Instagram DMCA Link Checker

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Write Google credentials
        shell: bash
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          set -euo pipefail
          if [[ "${GOOGLE_CREDENTIALS}" =~ ^\{ ]]; then
            printf '%s' "${GOOGLE_CREDENTIALS}" > credentials.json
          else
            printf '%s' "${GOOGLE_CREDENTIALS}" | base64 -d > credentials.json
          fi
          python - <<'PY'
import json; json.load(open("credentials.json")); print("credentials.json OK")
PY

      - name: Run script
        run: python check_instagram_links.py
