name: Instagram DMCA Link Checker

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright/python:v1.44.0-jammy
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Write Google credentials
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      - name: Run script
        run: python check_instagram_links.py
