name: Instagram Link Checker

on:
  workflow_dispatch:
    inputs:
      shard_index:
        description: "Shard index (0-based)"
        required: false
        default: "0"
      total_shards:
        description: "Total shards"
        required: false
        default: "1"
      skip_recent_days:
        description: "Skip rows with last-checked newer than N days"
        required: false
        default: "0"
  schedule:
    - cron: "0 2 * * *"  # 10 PM EST (2 AM UTC)

jobs:
  linkcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Write Google credentials
        shell: bash
        run: |
          if [ -z "${{ secrets.GOOGLE_CREDENTIALS }}" ]; then
            echo "ERROR: GOOGLE_CREDENTIALS secret is empty."
            exit 1
          fi
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Inspect credentials.json (debug)
        run: |
          wc -c credentials.json
          python - <<'PY'
import json, pathlib
b = pathlib.Path("credentials.json").read_bytes()
print("first byte:", b[:1])
print("keys:", sorted(json.loads(b.decode("utf-8")).keys()))
PY

      - name: Assert hardened loader present
        shell: bash
        run: |
          if grep -n "from_json_keyfile_name" check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
          sed -n '1,40p' check_instagram_links.py

      - name: Count current URLs in Logs!F
        id: count
        run: |
          TOTAL=$(python - <<'PY'
import json, gspread
from oauth2client.service_account import ServiceAccountCredentials
scope = [
  "https://spreadsheets.google.com/feeds",
  "https://www.googleapis.com/auth/drive",
]
with open("credentials.json","r",encoding="utf-8") as f:
    creds_dict = json.load(f)
creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
gc = gspread.authorize(creds)
ws = gc.open_by_key("1fFTIEDy-86lDaCgll1GkTq376hvrTd-DXulioXrDAgw").worksheet("Logs")
col = ws.col_values(6)  # Column F
print(sum(1 for v in col[1:] if (v or "").strip()))
PY
)
          echo "total=${TOTAL}" | tee -a "$GITHUB_OUTPUT"

      - name: Run script
        run: python -u check_instagram_links.py
        env:
          SHARD_INDEX: ${{ github.event.inputs.shard_index || 0 }}
          TOTAL_SHARDS: ${{ github.event.inputs.total_shards || 1 }}
          SKIP_RECENT_DAYS: ${{ github.event.inputs.skip_recent_days || 0 }}
