name: Insta Checker

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      sheet_key:
        description: "Sheet to run: primary | fb_rm | ig_rm"
        required: true
        default: "primary"
      total_shards:
        description: "Total shards"
        required: true
        default: "8"
      skip_recent_days:
        description: "Skip rows whose 'Last checked' is within N days (0=off)"
        required: true
        default: "0"

jobs:
  nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - sheet_key: primary
            shard: 0
          - sheet_key: primary
            shard: 1
          - sheet_key: primary
            shard: 2
          - sheet_key: primary
            shard: 3
          - sheet_key: primary
            shard: 4
          - sheet_key: primary
            shard: 5
          - sheet_key: primary
            shard: 6
          - sheet_key: primary
            shard: 7
          - sheet_key: fb_rm
            shard: 0
          - sheet_key: fb_rm
            shard: 1
          - sheet_key: fb_rm
            shard: 2
          - sheet_key: fb_rm
            shard: 3
          - sheet_key: fb_rm
            shard: 4
          - sheet_key: fb_rm
            shard: 5
          - sheet_key: fb_rm
            shard: 6
          - sheet_key: fb_rm
            shard: 7
          - sheet_key: ig_rm
            shard: 0
          - sheet_key: ig_rm
            shard: 1
          - sheet_key: ig_rm
            shard: 2
          - sheet_key: ig_rm
            shard: 3
          - sheet_key: ig_rm
            shard: 4
          - sheet_key: ig_rm
            shard: 5
          - sheet_key: ig_rm
            shard: 6
          - sheet_key: ig_rm
            shard: 7
    env:
      TOTAL_SHARDS: 8
      SKIP_RECENT_DAYS: 0
      SHEET_KEY: ${{ matrix.sheet_key }}
      SHARD_INDEX: ${{ matrix.shard }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade "playwright>=1.47.1"
          playwright install --with-deps chromium
      - shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            printf '%s' "${RAW_JSON:-}" > credentials.json
          fi
          test -s credentials.json
      - shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
      - run: python -u check_instagram_links.py

  prepare-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
      total:  ${{ steps.gen.outputs.total }}
      skip:   ${{ steps.gen.outputs.skip }}
    steps:
      - id: gen
        shell: bash
        run: |
          set -euo pipefail
          SHEET="${{ github.event.inputs.sheet_key }}"
          TOTAL="${{ github.event.inputs.total_shards }}"
          SKIP="${{ github.event.inputs.skip_recent_days }}"
          inc=""
          for ((i=0;i<TOTAL;i++)); do
            if [[ -n "$inc" ]]; then inc="$inc,"; fi
            inc="$inc{\"sheet_key\":\"$SHEET\",\"shard\":$i}"
          done
          echo "matrix={\"include\":[${inc}]}" >> "$GITHUB_OUTPUT"
          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"
          echo "skip=$SKIP"   >> "$GITHUB_OUTPUT"

  manual:
    if: github.event_name == 'workflow_dispatch'
    needs: prepare-manual
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-manual.outputs.matrix) }}
    env:
      SHEET_KEY: ${{ matrix.sheet_key }}
      SHARD_INDEX: ${{ matrix.shard }}
      TOTAL_SHARDS: ${{ needs.prepare-manual.outputs.total }}
      SKIP_RECENT_DAYS: ${{ needs.prepare-manual.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade "playwright>=1.47.1"
          playwright install --with-deps chromium
      - shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            printf '%s' "${RAW_JSON:-}" > credentials.json
          fi
          test -s credentials.json
      - shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
      - run: python -u check_instagram_links.py
