name: Instagram DMCA Link Checker

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright Browsers
        run: |
          pip install playwright
          python -m playwright install chromium

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Write Google credentials
        shell: bash
        run: |
          printf '%s' "$GOOGLE_CREDENTIALS" > credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run script
        run: python check_instagram_links.py
