name: Link check (Logs sheet)

on:
  workflow_dispatch:
    inputs:
      shard_index:
        description: "Shard index (0-based)"
        default: "0"
        required: true
      total_shards:
        description: "Total shards"
        default: "1"
        required: true
      skip_recent_days:
        description: "Skip rows with last-checked newer than N days"
        default: "0"
        required: true
  schedule:
    # 03:00 UTC == 10:00 PM EST (standard time)
    - cron: "0 3 * * *"

jobs:
  linkcheck:
    runs-on: ubuntu-22.04
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Write Google credentials
        shell: bash
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          python - <<'PY'
import os, base64, sys
raw = os.environ.get("GOOGLE_CREDENTIALS_JSON","").strip()
if not raw:
    print("ERROR: GOOGLE_CREDENTIALS_JSON secret is empty.", file=sys.stderr)
    sys.exit(1)
try:
    data = raw.encode("utf-8") if raw.lstrip().startswith("{") else base64.b64decode(raw)
    open("credentials.json","wb").write(data)
    print("credentials.json written:", len(data), "bytes")
except Exception as e:
    print("ERROR writing credentials.json:", e, file=sys.stderr)
    sys.exit(1)
PY

      - name: Inspect credentials.json (debug)
        run: |
          wc -c credentials.json
          python - <<'PY'
import json, pathlib
b = pathlib.Path("credentials.json").read_bytes()
print("first byte:", b[:1])
try:
    print("keys:", sorted(json.loads(b.decode("utf-8")).keys()))
except Exception as e:
    print("json error:", e)
PY

      - name: Count current URLs in Logs!F
        id: count
        run: |
          TOTAL=$(python - <<'PY'
import json, gspread
from oauth2client.service_account import ServiceAccountCredentials

SHEET_ID = "1fFTIEDy-86lDaCgll1GkTq376hvrTd-DXulioXrDAgw"
TAB = "Logs"
URL_COL = 6  # Column F

scope = [
  "https://spreadsheets.google.com/feeds",
  "https://www.googleapis.com/auth/drive",
]
with open("credentials.json","r",encoding="utf-8") as f:
    creds_dict = json.load(f)
creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
gc = gspread.authorize(creds)

ws = gc.open_by_key(SHEET_ID).worksheet(TAB)
col = ws.col_values(URL_COL)
print(sum(1 for v in col[1:] if (v or "").strip()))
PY
          )
          echo "total=$TOTAL" | tee -a "$GITHUB_OUTPUT"

      - name: Run script
        run: python -u check_instagram_links.py
        env:
          SHARD_INDEX: ${{ github.event.inputs.shard_index || 0 }}
          TOTAL_SHARDS: ${{ github.event.inputs.total_shards || 1 }}
          SKIP_RECENT_DAYS: ${{ github.event.inputs.skip_recent_days || 0 }}
