name: Insta Checker

on:
  workflow_dispatch:

jobs:
  run-checker:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # Write credentials.json correctly. If the secret is base64, decode it.
      - name: Write Google credentials
        shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            echo "Using GOOGLE_CREDENTIALS_B64"
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            echo "Using GOOGLE_CREDENTIALS"
            # printf preserves exact bytes; echo may mangle newlines/backslashes
            printf '%s' "$RAW_JSON" > credentials.json
          fi
          # Quick sanity check that file starts with '{' and ends with '}'
          head -c 1 credentials.json | grep -q '{'
          tail -c 1 credentials.json | grep -q '}' || true

      - name: Inspect credentials.json (debug)
        run: >
          python -c "import json, pathlib;
          b=pathlib.Path('credentials.json').read_bytes();
          print('len:', len(b), 'first:', b[:1]);
          obj=json.loads(b.decode('utf-8'));
          print('keys:', sorted(obj.keys()))"

      - name: Assert hardened loader present
        shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo 'ERROR: old keyfile_name loader found; refusing to run.'
            exit 1
          fi

      - name: Run script
        run: python -u check_instagram_links.py
