name: Instagram DMCA Link Checker

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install Playwright system deps
        uses: microsoft/playwright-github-action@v1

      - name: Install Chromium browser
        run: python -m playwright install chromium

      - name: Write Google credentials
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          echo "$GOOGLE_CREDENTIALS_JSON" > credentials.json

      - name: Run script
        run: python check_instagram_links.py
