name: Instagram DMCA Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS || secrets.GOOGLE_CREDENTIALS_JSON }}
      GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS || secrets.GOOGLE_CREDENTIALS_JSON }}
      PYTHONWARNINGS: ignore::DeprecationWarning

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-ms-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-ms-playwright-

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Prepare Google credentials (raw JSON or base64)
        run: python scripts/prepare_google_creds.py

      - name: Run script
        run: python check_instagram_links.py
