name: Insta Checker

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      sheet:
        description: "primary | fb_rm | ig_rm"
        required: false
        default: "primary"
      total_shards:
        description: "Total shards (e.g. 8)"
        required: false
        default: "8"
      skip_recent_days:
        description: "Skip rows whose 'Last checked' is within N days (0=off)"
        required: false
        default: "0"

jobs:
  nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        sheet: [primary, fb_rm, ig_rm]
        shard: [0,1,2,3,4,5,6,7]
    env:
      SHEET_NAME: ${{ matrix.sheet }}
      SHARD_INDEX: ${{ matrix.shard }}
      TOTAL_SHARDS: 8
      SKIP_RECENT_DAYS: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade "playwright>=1.47.1"
          playwright install --with-deps chromium webkit
      - name: Write Google credentials
        shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            printf '%s' "${RAW_JSON:-}" > credentials.json
          fi
          test -s credentials.json
      - name: Refuse deprecated keyfile loader
        shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
      - name: Run checker (nightly shards)
        env:
          SHEET_NAME: ${{ env.SHEET_NAME }}
          SHARD_INDEX: ${{ env.SHARD_INDEX }}
          TOTAL_SHARDS: ${{ env.TOTAL_SHARDS }}
          SKIP_RECENT_DAYS: ${{ env.SKIP_RECENT_DAYS }}
        run: python -u check_instagram_links.py

  prepare-manual:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.mk.outputs.matrix }}
      total:  ${{ steps.mk.outputs.total }}
      skip:   ${{ steps.mk.outputs.skip }}
      sheet:  ${{ steps.mk.outputs.sheet }}
    steps:
      - id: mk
        shell: bash
        run: |
          set -euo pipefail
          SHEET="${{ github.event.inputs.sheet || 'primary' }}"
          TOTAL="${{ github.event.inputs.total_shards || '8' }}"
          SKIP="${{ github.event.inputs.skip_recent_days || '0' }}"

          [[ "$TOTAL" =~ ^[0-9]+$ ]] || TOTAL=8
          (( TOTAL >= 1 )) || TOTAL=8

          inc=''
          for ((i=0;i<TOTAL;i++)); do
            [[ -n "$inc" ]] && inc="$inc,"
            inc="$inc"{\"sheet\":\"$SHEET\",\"shard\":$i}
          done
          MATRIX="{\"include\":[${inc}]}"
          {
            echo "matrix=$MATRIX"
            echo "total=$TOTAL"
            echo "skip=$SKIP"
            echo "sheet=$SHEET"
          } >> "$GITHUB_OUTPUT"

  manual:
    if: github.event_name == 'workflow_dispatch'
    needs: prepare-manual
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-manual.outputs.matrix) }}
    env:
      SHEET_NAME: ${{ matrix.sheet }}
      SHARD_INDEX: ${{ matrix.shard }}
      TOTAL_SHARDS: ${{ needs.prepare-manual.outputs.total }}
      SKIP_RECENT_DAYS: ${{ needs.prepare-manual.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade "playwright>=1.47.1"
          playwright install --with-deps chromium webkit
      - name: Write Google credentials
        shell: bash
        env:
          RAW_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          B64_JSON: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          set -euo pipefail
          if [[ -n "${B64_JSON:-}" ]]; then
            printf '%s' "$B64_JSON" | base64 -d > credentials.json
          else
            printf '%s' "${RAW_JSON:-}" > credentials.json
          fi
          test -s credentials.json
      - name: Refuse deprecated keyfile loader
        shell: bash
        run: |
          if grep -nE 'from_json_keyfile_name[[:space:]]*\(' check_instagram_links.py; then
            echo "ERROR: old keyfile_name loader found; refusing to run."
            exit 1
          fi
      - name: Run checker (manual shards)
        env:
          SHEET_NAME: ${{ env.SHEET_NAME }}
          SHARD_INDEX: ${{ env.SHARD_INDEX }}
          TOTAL_SHARDS: ${{ env.TOTAL_SHARDS }}
          SKIP_RECENT_DAYS: ${{ env.SKIP_RECENT_DAYS }}
        run: python -u check_instagram_links.py
